---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuqiang.
--- DateTime: 2021/6/2 9:57 上午
---
local core = require("apisix.core")
local _M = {}

--- 用于判断数组元素内容
--- 创建一个reserve的table， 将table的值作为键存储为一个新的table
function _M.rev_tab(old_tab)
    local rev_tab = {}
    for _, v in ipairs(old_tab) do
        rev_tab[tostring(v)] = true
    end
    return rev_tab
end

return _M
